name: Rust

on:
  push:
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Pcap
      run: sudo apt install libpcap-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
